#!/usr/bin/env python
"""
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  This file is part of the Smart Developer Hub Project:
    http://www.smartdeveloperhub.org

  Center for Open Middleware
        http://www.centeropenmiddleware.com/
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Copyright (C) 2015 Center for Open Middleware.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
"""

# Import Generator files
import download

# Import other libraries
import settings

__author__ = 'Alejandro F. Carrera'

# Main

if __name__ == '__main__':
    settings.print_message(" * [%s] Started" % settings.LONGNAME)

    # Get and Clone Repository
    __repo = download.get_repo()

    # Get Branches information
    __branches = __repo.branches.keys()
    settings.print_message(" * [%s] Number of branches %d" %
                           (settings.LONGNAME, len(__branches)))

    # Get Branches information (only selected branches)
    __real_branches = []
    if settings.GEN_BRANCH is None:
        __real_branches = __branches
    else:
        for i in __branches:
            if settings.GEN_BRANCH in i:
                __real_branches.append(i)
        settings.print_message(" * [%s] Number of branches (%s) %d" %
                               (settings.LONGNAME, settings.GEN_BRANCH,
                                len(__real_branches)))

    settings.print_message(" * [%s] Finished" % settings.LONGNAME)

